sonars:
  - sonar1:
    X: 50.2
    y: 0
    th: 0
  - sonar2:
    X: 35.7
    y: -126
    th: -0.54
  - sonar3:
    X: -18
    y: -141.5
    th: -1.22
  - sonar4:
    X: -80
    y: -131
    th: -1.88
  - sonar5:
    X: -174.5
    y: -63
    th: -2.46
  - sonar6:
    X: -189.8
    y: 0
    th: 3.14
  - sonar7:
    X: -174.5
    y: 63
    th: 2.46
  - sonar8:
    X: -80
    y: 131
    th: 1.88
  - sonar9:
    X: -18
    y: 141.5
    th: 1.22
  - sonar10:
    X: 37
    y: 126
    th: 0.54
  - sonar11:
    X: 0
    y: 0
    th: 0


